"""
Django settings for phone_store project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-lv*uf*b$kgqqr1yxx^$vawk2ygx7b8so@4&kbu(r_w&m_4-jqn'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Hôtes autorisés : en production, définissez DJANGO_ALLOWED_HOSTS
# (ex. "votre-nom.pythonanywhere.com,www.exemple.mg")
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS if h.strip()]

# URL officielle du site (utilisée par le QR code de la page Contact).
# En production, définissez DJANGO_SITE_URL (ex. "https://hoby2108.pythonanywhere.com").
# Si vide, le QR code détecte automatiquement le domaine de la requête.
SITE_URL = os.environ.get('DJANGO_SITE_URL', '').rstrip('/')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'boutique.apps.BoutiqueConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'phone_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'boutique.context_processors.panier_global',
                'boutique.context_processors.notifications_global',
            ],
        },
    },
]

WSGI_APPLICATION = 'phone_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Indian/Antananarivo'

USE_I18N = True

USE_TZ = True

# ============================================================
# A U T H E N T I F I C A T I O N
# ============================================================

LOGIN_URL = 'connexion'
LOGIN_REDIRECT_URL = 'accueil'
LOGOUT_REDIRECT_URL = 'accueil'

# Email : en développement, les emails (lien de réinitialisation de mot de
# passe, messages de contact) sont affichés dans la console du serveur.
# Pour l'envoi réel, définissez les variables d'environnement SMTP
# (voir DEPLOIEMENT.md — section « Emails »).
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'

if EMAIL_HOST and EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', 'Phone Store <no-reply@phonestore.mg>'
)

# Adresse de réception des messages envoyés via le formulaire de contact
CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', 'rakotoarijaona04@yahoo.com')

# Media (fichiers uploadés : produits, vidéos, photos de profil)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# P A I E M E N T S
# ============================================================
# Laissez les clés vides → le site fonctionne en MODE DÉMO
# (les paiements sont simulés pour tester le parcours complet).
#
# Pour passer en réel, remplissez les clés (idéalement via des variables
# d'environnement, pas en dur ici).

# --- Stripe (cartes Visa / Mastercard / Amex / Apple Pay / Google Pay) ---
STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')

# --- PayPal ---
PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID', '')
PAYPAL_CLIENT_SECRET = os.environ.get('PAYPAL_CLIENT_SECRET', '')
PAYPAL_ENV = os.environ.get('PAYPAL_ENV', 'sandbox')  # 'sandbox' ou 'live'

# --- Orange Money (API marchand) ---
ORANGE_MONEY_CLIENT_ID = os.environ.get('ORANGE_MONEY_CLIENT_ID', '')
ORANGE_MONEY_CLIENT_SECRET = os.environ.get('ORANGE_MONEY_CLIENT_SECRET', '')
ORANGE_MONEY_MERCHANT_NUMBER = os.environ.get('ORANGE_MONEY_MERCHANT_NUMBER', '')
ORANGE_MONEY_BASE_URL = os.environ.get('ORANGE_MONEY_BASE_URL', 'https://api.orange.com')

# --- Devise / conversion ---
# L'Ariary (MGA) n'est pas accepté par Stripe/PayPal : le montant est converti
# en EUR pour les cartes et PayPal. Ajustez le taux selon le cours du jour.
PAIEMENT_TAUX_EUR = float(os.environ.get('PAIEMENT_TAUX_EUR', '5000'))  # 1 EUR = 5000 Ar

# ============================================================
# P R O D U C T I O N  (statiques + sécurité)
# ============================================================
# Les fichiers statiques sont collectés dans staticfiles/ puis servis
# par WhiteNoise (aucun serveur externe requis).
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Sécurité renforcée en production
if not DEBUG:
    # Le site est derrière un reverse proxy (PythonAnywhere) : permet à Django
    # de détecter HTTPS via l'en-tête X-Forwarded-Proto (nécessaire pour que le
    # QR code généré dynamiquement encode bien une URL https://)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    CSRF_COOKIE_SECURE = os.environ.get('DJANGO_CSRF_COOKIE_SECURE', 'False') == 'True'
    SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SESSION_COOKIE_SECURE', 'False') == 'True'
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'False') == 'True'