# Generated by Django 6.0.3 on 2026-08-11 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_commande_messagecontact_avis_lignecommande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('carte', 'Carte bancaire (Visa, Mastercard)'), ('paypal', 'PayPal'), ('orange_money', 'Orange Money'), ('especes', 'Paiement à la livraison')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=200)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('email_payeur', models.EmailField(blank=True, default='', max_length=254)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='boutique.commande')),
            ],
        ),
    ]
