# Generated by Django 6.1 on 2026-09-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_profil_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='est_pilote_principal',
            field=models.BooleanField(default=False, help_text='Accès réservé au dashboard administrateur principal.'),
        ),
    ]
