# Generated by Django 6.1 on 2026-09-14 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_profil_est_pilote_principal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_reacteur', models.CharField(db_index=True, max_length=64)),
                ('type_reaction', models.CharField(choices=[('aime', "J'aime"), ('adore', "J'adore"), ('wow', 'Wow !')], default='aime', max_length=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='boutique.produit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('produit', 'cle_reacteur'), name='reaction_unique_par_reacteur')],
            },
        ),
    ]
